resume_app/urls.py
from django.urls import path
from resume_app import views

app_name = 'resume_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('generate_resume1/', views.generate_resume1, name='generate_resume1'),
    path('generate_resume2/', views.generate_resume2, name='generate_resume2'),
    path('generate_resume3/', views.generate_resume3, name='generate_resume3'),
    path('generate_resume4/', views.generate_resume4, name='generate_resume4'),
    path('generate_resume5/', views.generate_resume5, name='generate_resume5'),
    path('generate_resume6/', views.generate_resume6, name='generate_resume6'),
    path('generate_resume7/', views.generate_resume7, name='generate_resume7'),
    path('generate_resume8/', views.generate_resume8, name='generate_resume8'),
    path('generate_resume9/', views.generate_resume9, name='generate_resume9'),
    path('generate_resume10/', views.generate_resume10, name='generate_resume10'),
    path('generate_resume11/', views.generate_resume11, name='generate_resume11'),
    path('generate_resume12/', views.generate_resume12, name='generate_resume12'),
    path('generate_resume13/', views.generate_resume13, name='generate_resume13'),
    path('generate_resume14/', views.generate_resume14, name='generate_resume14'),
    path('generate_resume15/', views.generate_resume15, name='generate_resume15'),
    path('api/save_image/', views.save_image, name='save_image'),
]

test_resume_generator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("resume_app.urls"))
]

resume_app/models.py
from django.db import models

# Create your models here.

resume_app/views.py
from django.shortcuts import render, redirect
import json
import openai
from django.conf import settings
from django.http import JsonResponse


openai.api_key = "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"
messages = []

def complete_content(content):
    # Retrieve the values of the dynamically generated work experience fields
    work_experience_values = {}
    edu_experience_values = {}
    name, title, summary, skills = "", "", "", ""

    # print(request.POST.items())
    # for key, value in request.POST.items():
        # print(key, '--', value)
    for key, value in content:
        if key.startswith('workTitle') or key.startswith('workCompany') or key.startswith('workDate') or key.startswith('workDescription'):
            field_name, field_index = key.split('_', 1)  # Split the key into name and index
            if field_index not in work_experience_values:
                work_experience_values[field_index] = {}  # Create a dictionary for the index if it doesn't exist
            work_experience_values[field_index][field_name] = value
        
        if key.startswith('eduDegree') or key.startswith('eduSchool') or key.startswith('eduDate') or key.startswith('eduDescription'):
            field_name, field_index = key.split('_', 1)  # Split the key into name and index
            if field_index not in edu_experience_values:
                edu_experience_values[field_index] = {}  # Create a dictionary for the index if it doesn't exist
            edu_experience_values[field_index][field_name] = value
        
        if key.startswith('name'):
            name = value
        if key.startswith('title'):
            title = value
        if key.startswith('address'):
            address = value
        if key.startswith('email'):
            email = value
        if key.startswith('github'):
            github = value
        if key.startswith('linkedin'):
            linkedin = value
        if key.startswith('phone'):
            phone = value
        if key.startswith('summary'):
            summary = value
        if key.startswith('skills'):
            skills = value

        
    
    # Process the values and generate the resume
    
    # Pass the processed values to the template
    context = {
        'name': name,
        'title': title,
        'address': address,
        'email': email,
        'github': github,
        'linkedin': linkedin,
        'phone': phone,
        'summary': summary,
        'skills': skills,
        'work_experience_values': work_experience_values,
        'edu_experience_values': edu_experience_values,
        # Add other processed values as needed
    }

    message = json.dumps(context)
    messages.append({"role": "system", "content": message})
    messages.append({"role": "user", "content": """
                Please generate professional resume contents with above information.
                It should be the professional format.
                Please modify all of contents with state-of-the-art techs and methodologies.
                Add more information to summary and work experience.
                Answer should contain Name, Address, Gmail, Linkedin, Summary, Experience, Skills, Projects and Education parts and also JSON format like this:
                {
                    "name" : "Paht",
                    "title" : "Senior ML engineer", 
                    "summary": "Passionate and Innovative Software Engineer with relevant skills and experiences with Artificial Intelligence and Software Development. Rich experience of computer science and AI/ML/DE/DS including Computer Vision, Natural Language Processing, Application Development and provide solutions to the business and enterprise with 10 years of experience with software development and analyzing skills",
                    "workExperience":[ 
                        {
                            "dates": "05/2012 - 12/2020",
                            "company": "XOOJ",
                            "title": "Machine Learning Engineer",
                            "description": ["Expertized in establishing MLOps pipeline for projects and ML algorithms including regression, classification, clustering.", 
                                "Skillfully experienced with various types of ML algorithms, fine-tuning of hyperparameters, weight optimization.",
                                "Professionally experienced with AWS Lambda, Sagemaker, Kinesis, Firehose, Glue, Athena, EKS, EMR, Redshift, CodeBuild, CodeCommit and led as a technical advisor.",
                                "Experienced with Generative AI including ChatGPT, GPT4, Stable Diffusion, Midjourney and TTS, STT."]
                        },
                        {
                            "dates": "01/2021 - 12/2022",
                            "company": "Microsoft",
                            "title": "Senior Machine Learning Engineer",
                            "description": ["Implemented Cloud based 10+ Machine Learning projects with the combination of coding, relational database, MySQL, Oracle, Computer Science, NLP and data-driven projects such as AI Poster, CRM and Recommendation System. ",
                                "Fully experienced with several data formats and over 4 ETL, ELT tools. ",
                                "Completed 10+ Deep Learning based computer vision, NLP projects using frameworks such as Tensorflow, PyTorch, Yolo Model and successfully deployed 5+ large-scale production AI solutions."]
                        },
                        {
                            "dates": "01/2021 - 12/2022",
                            "company": "Microsoft",
                            "title": "Senior Machine Learning Engineer",
                            "description": ["Implemented Cloud based 10+ Machine Learning projects with the combination of coding, relational database, MySQL, Oracle, Computer Science, NLP and data-driven projects such as AI Poster, CRM and Recommendation System. ",
                                "Fully experienced with several data formats and over 4 ETL, ELT tools. ",
                                "Completed 10+ Deep Learning based computer vision, NLP projects using frameworks such as Tensorflow, PyTorch, Yolo Model and successfully deployed 5+ large-scale production AI solutions."]
                        }
                    ]
                    ,
                    "contactInfo": 
                        {
                            "address": "abc street",
                            "email": "john@gmail.com",
                            "github": "github.com/devexpert0101",
                            "linkedin": "linkedin.com/in/Paht",
                            "phone": "+12316512245"
                        }
                    ,
                    "education": [
                        {
                            "dates": "04/2010 - 06/2014",
                            "school": "University of Pennsylvania",
                            "degree": "Bachelor's Degree of Computer Science",
                            "description": ""
                        }
                    ]
                    ,
                    "skills" : ["Python", "C++" ,"C#", "HTML", "CSS", "Java", "JavaScript"]
                    }
        """})
    
    # chat = openai.ChatCompletion.create(
    #         model='gpt-3.5-turbo', messages=messages
    #     )

    # reply = chat.choices[0].message.content


    # jsondata = json.loads(reply)


    tmpdata = {
                    "name" : "Paht",
                    "title" : "Senior ML engineer", 
                    "summary": "Passionate and Innovative Software Engineer with relevant skills and experiences with Artificial Intelligence and Software Development. Rich experience of computer science and AI/ML/DE/DS including Computer Vision, Natural Language Processing, Application Development and provide solutions to the business and enterprise with 10 years of experience with software development and analyzing skills.",
                    "workExperience":[ 
                        {
                            "dates": "05/2012 - 12 /2020",
                            "company": "XOOJ",
                            "title": "Machine Learning Engineer",
                            "description": ["Expertized in establishing MLOps pipeline for projects and ML algorithms including regression, classification, clustering.", 
                                "Skillfully experienced with various types of ML algorithms, fine-tuning of hyperparameters, weight optimization.",
                                "Professionally experienced with AWS Lambda, Sagemaker, Kinesis, Firehose, Glue, Athena, EKS, EMR, Redshift, CodeBuild, CodeCommit and led as a technical advisor.",
                                "Experienced with Generative AI including ChatGPT, GPT4, Stable Diffusion, Midjourney and TTS, STT."]
                        },
                        {
                            "dates": "01/2021 - 12 /2022",
                            "company": "Microsoft",
                            "title": "Senior Machine Learning Engineer",
                            "description": ["Implemented Cloud based 10+ Machine Learning projects with the combination of coding, relational database, MySQL, Oracle, Computer Science, NLP and data-driven projects such as AI Poster, CRM and Recommendation System. ",
                                "Fully experienced with several data formats and over 4 ETL, ELT tools. ",
                                "Completed 10+ Deep Learning based computer vision, NLP projects using frameworks such as Tensorflow, PyTorch, Yolo Model and successfully deployed 5+ large-scale production AI solutions."]
                        },
                        {
                            "dates": "01/2021 - 12 /2022",
                            "company": "Microsoft",

resume_app/templates/resume_app/index.html
<!DOCTYPE html>
<html>

<head>
    <title>Resume Generator</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'styles/index.css' %}">
    <script src="{% static 'resume_app/js/script.js' %}"></script>
</head>

<body>
    <h1>Resume Generator</h1>
    <!-- <form id="resumeForm" action="{% url 'resume_app:generate_resume1' %}" method="POST"> -->
    <form id="resumeForm" method="POST">
        {% csrf_token %}
        <div class="container">
                        
            <div class="info">
                <div>
                    <div>
                        <p><input type="file"   accept="image/*" name="image" id="file"  onchange="loadFile(event)" style="display: none;"></p>
                        <p><label for="file" class="button_upload" style="cursor: pointer;">Upload Image</label></p>
                        <p><img id="output" width="200" /></p>
                    </div>
                    
                    <div class="form-row">
                        <label for="name">Name:</label>
                    </div>
                    <div>
                        <input type="text" id="name" name="name"><br><br>
                    </div>
                    <div class="form-row">
                        <label for="name">Title:</label>
                    </div>
                    <div>
                        <input type="text" id="title" name="title"><br><br>
                    </div>
                </div>

                <h2>Sections</h2>
                <div id="tabs">
                    <button class="tablink" onclick="openSection(event, 'contact')">Contact Info</button>
                    <button class="tablink" onclick="openSection(event, 'summary')">Summary</button>
                    <button class="tablink" onclick="openSection(event, 'work')">Work Experience</button>
                    <button class="tablink" onclick="openSection(event, 'edu')">Education</button>
                    <button class="tablink" onclick="openSection(event, 'skills')">Skills</button>
                    <!-- Add more buttons for additional sections -->
                </div>


                <div id="contact" class="section">
                    <h3>Contact Info</h3>
                    <label for="address">Address</label>
                    <input type="text" id="address" name="address">

                    <label for="email">Email</label>
                    <input type="text" id="email" name="email">

                    <label for="github">GitHub</label>
                    <input type="text" id="github" name="github">

                    <label for="email">LinkedIn</label>
                    <input type="text" id="linkedin" name="linkedin">

                    <label for="email">Phone</label>
                    <input type="text" id="phone" name="phone">

                    <!-- Add more fields for contact information -->
                </div>

                <div id="summary" class="section">
                    <h3>Summary</h3>
                    <textarea id="summaryText" name="summaryText" rows="4" cols="50"></textarea><br><br>

                    <!-- Add more fields for the summary section -->
                </div>

                <div id="work" class="section">
                    <h3>Work Experience</h3>
                    <button onclick="addWorkExperience(event)">Add Work Experience</button>
                    <div id="workExperience" class="section-experience">
                        <label for="workTitle_0">Title</label>
                        <input type="text" id="workTitle_0" name="workTitle_0">

                        <label for="workCompany_0">Company</label>
                        <input type="text" id="workCompany_0" name="workCompany_0">

                        <label for="workDate_0">Date</label>
                        <input type="text" id="workDate_0" name="workDate_0">

                        <label for="workDescription_0">Description</label>
                        <textarea id="workDescription_0" name="workDescription_0" rows="4" cols="50"></textarea><br><br>
                    </div>

                </div>

                <!-- Add more fields for the work experience section -->

                <div id="edu" class="section">
                    <h3>Education</h3>
                    <button onclick="addEducation(event)">Add Education</button>
                    <div id="education" class="section-education">
                        <label for="eduDegree_0">Degree</label>
                        <input type="text" id="eduDegree_0" name="eduDegree_0">

                        <label for="eduSchool_0">School</label>
                        <input type="text" id="eduSchool_0" name="eduSchool_0">

                        <label for="eduDate_0">Date</label>
                        <input type="text" id="eduDate_0" name="eduDate_0">

                        <label for="eduDescription_0">Description</label>
                        <textarea id="eduDescription_0" name="eduDescription_0" rows="4" cols="50"></textarea><br><br>
                    </div>

                </div>

                <div id="skills" class="section">
                    <h3>Skills</h3>
                    <textarea id="skillArea" name="skills" rows="4" , cols="50"></textarea><br><br>
                </div>
            </div>

            <div class="button-group">
                <div id = "button1" onclick="submitForm('/generate_resume1/')">
                    <img src="{% static 'images/1.png' %}" style="width: inherit;" />
                </div>
                <div id = "button1" onclick="submitForm('/generate_resume2/')">
                    <img src="{% static 'images/2.png' %}" style="width: inherit;" />
                </div>
                <div id = "button1" onclick="submitForm('/generate_resume3/')">
                    <img src="{% static 'images/3.png' %}" style="width: inherit;" />
                </div>
                <div id = "button1" onclick="submitForm('/generate_resume4/')">
                    <img src="{% static 'images/4.png' %}" style="width: inherit;" />
                </div>
                <div id = "button1" onclick="submitForm('/generate_resume5/')">
                    <img src="{% static 'images/5.png' %}" style="width: inherit;" />
                </div>
                <div id = "button1" onclick="submitForm('/generate_resume6/')">
                    <img src="{% static 'images/6.png' %}" style="width: inherit;" />
                </div>
                <div id = "button1" onclick="submitForm('/generate_resume7/')">
                    <img src="{% static 'images/7.png' %}" style="width: inherit;" />
                </div>
                <div id = "button1" onclick="submitForm('/generate_resume8/')">
                    <img src="{% static 'images/8.png' %}" style="width: inherit;" />
                </div>
                <div id = "button1" onclick="submitForm('/generate_resume9/')">
                    <img src="{% static 'images/9.png' %}" style="width: inherit;" />
                </div>
                <div id = "button1" onclick="submitForm('/generate_resume10/')">
                    <img src="{% static 'images/10.png' %}" style="width: inherit;" />
                </div>
                <div id = "button1" onclick="submitForm('/generate_resume11/')">
                    <img src="{% static 'images/11.png' %}" style="width: inherit;" />
                </div>
                <div id = "button1" onclick="submitForm('/generate_resume12/')">
                    <img src="{% static 'images/12.png' %}" style="width: inherit;" />
                </div>
                <div id = "button1" onclick="submitForm('/generate_resume13/')">
                    <img src="{% static 'images/13.png' %}" style="width: inherit;" />
                </div>
                <div id = "button1" onclick="submitForm('/generate_resume14/')">
                    <img src="{% static 'images/14.png' %}" style="width: inherit;" />
                </div>
                <div id = "button1" onclick="submitForm('/generate_resume15/')">
                    <img src="{% static 'images/15.png' %}" style="width: inherit;" />
                </div>
                
            </div>
        </div>

    </form>

    {% load static %}
    <script>
        function openSection(evt, sectionName) {

            evt.preventDefault();
            var i, section, tablink;

            // Hide all sections
            section = document.getElementsByClassName("section");
            for (i = 0; i < section.length; i++) {
                section[i].style.display = "none";
            }

            // Deactivate all tablinks
            tablink = document.getElementsByClassName("tablink");
            for (i = 0; i < tablink.length; i++) {
                tablink[i].className = tablink[i].className.replace(" active", "");
            }

            // Show the selected section and activate the corresponding tablink
            document.getElementById(sectionName).style.display = "flex";
            document.getElementById(sectionName).style.flexDirection = "column";
            document.getElementById(sectionName).style.alignItems = "flex-start";
            document.getElementById(sectionName).style.marginBottom = "10px";
            evt.currentTarget.className += " active";
        }

        var workExperienceCount = 1;

        function addWorkExperience() {
            event.preventDefault();
            var workExperience = document.getElementById("work");

            // Create a new set of fields
            var newFields = document.createElement("div");
            newFields.innerHTML = `
                <label for="workTitle_${workExperienceCount}">Title</label>
                <input type="text" id="workTitle_${workExperienceCount}" name="workTitle_${workExperienceCount}">
        
                <label for="workCompany_${workExperienceCount}">Company</label>
                <input type="text" id="workCompany_${workExperienceCount}" name="workCompany_${workExperienceCount}">

                <label for="workDate_${workExperienceCount}">Date</label>
                <input type="text" id="workDate_${workExperienceCount}" name="workDate_${workExperienceCount}">
        
                <label for="workDescription_${workExperienceCount}">Description</label>
                <textarea id="workDescription_${workExperienceCount}" name="workDescription_${workExperienceCount}" rows="4" cols="50"></textarea><br><br>
            `;

            // Append the new fields to the work experience section
            workExperience.appendChild(newFields);

            // Increment the work experience count for unique names
            workExperienceCount++;
        }
        function addEducation(event) {
            event.preventDefault();

            var educationDiv = document.getElementById("education");

            var eduDegree = document.createElement("input");
            eduDegree.type = "text";
            eduDegree.name = "eduDegree";
            eduDegree.placeholder = "Degree";
            educationDiv.appendChild(eduDegree);

            var eduSchool = document.createElement("input");
            eduSchool.type = "text";
            eduSchool.name = "eduSchool";
            eduSchool.placeholder = "School";
            educationDiv.appendChild(eduSchool);

            var eduDate = document.createElement("input");
            eduDate.type = "text";
            eduDate.name = "eduDate";
            eduDate.placeholder = "Date";
            educationDiv.appendChild(eduDate);

            var eduDescription = document.createElement("textarea");
            eduDescription.name = "eduDescription";
            eduDescription.rows = "4";
            eduDescription.cols = "50";
            eduDescription.placeholder = "Description";
            educationDiv.appendChild(eduDescription);

            educationDiv.appendChild(document.createElement("br"));
        }

        function submitForm(page) {
            var form = document.getElementById('resumeForm');
            // form.action = page + '.html';  // Set the action URL based on the clicked button
            form.action = page
            form.submit();  // Submit the form
        }

        var loadFile = function(event) {
            var image = document.getElementById('output');
            image.src = URL.createObjectURL(event.target.files[0]);
            var file = event.target.files[0];

            // // Create a temporary anchor tag
            // var downloadLink = document.createElement('a');
            // downloadLink.href = URL.createObjectURL(file);
            // var url = "{% static 'images/myphoto.jpg' %}"
            // downloadLink.download = url;

            // // Trigger a click event to start the download
            // downloadLink.click();

            var formData = new FormData();
            formData.append('image', file);

            fetch('/api/save_image/', {
                method: 'POST',
                body: formData
            })
            .then(response = response.json())
            .then(data=>{
                if (data.status == 'success') {
                    console.log('success')
                }
            })
            .catch(error => {
                console.log('Error saving image:', error);
            });
        };
    </script>
</body>

</html>

resume_app/templates/resume_app/resume1.html
<html>

<head>
    {% load static %}

    <link rel="stylesheet" href="{% static 'styles/resume1.css' %}">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js">
    </script>
</head>

<body>

    <!-- <button id="download-button">generate PDF</button>
    <div id="editor"></div> -->
    <button class="btn btn-block no-print btn-success" onclick="window.print()">PRINT AS PDF</button>

    <div class='parent' id="content">
        <div class="left">
            <div class="inner">
                <div class="name-hero">

                    <div class="name-text">
                        <h3>{{name}} </h3>
                    </div>

                    <div class="title">
                        <h3> {{title}} </h3>
                    </div>
                </div>


                <div class="summary">
                    <h1>Summary</h1>
                    <p>{{summary}}</p>
                </div>
                <section>
                    <h1>Employment</h1>
                    {% for experience in workExperience %}
                    <p><em>{{experience.dates}} | {{experience.company}} | {{experience.title}}</em></p>                    

                    {% for line in experience.description %}
                    <p>
                        <li>{{line}}</li>
                    </p>
                    {% endfor %}

                    {% endfor %}
                </section>
                <section>
                    <h1>Education</h1>
                    {% for edu in education %}
                    <p><em>{{edu.dates}} | {{edu.school}} | {{edu.degree}}</em></p>
                    <p>{{edu.description}}</p>

                    {% endfor %}
                </section>


            </div>
        </div>
        <div class="right">
            <h2>Contact Information</h2>
            <p>Email: {{contactInfo.email}}</p>
            <p>Phone: {{contactInfo.phone}}</p>
            <p>Address: {{contactInfo.address}}</p>           
            <p>LinkedIn: {{contactInfo.linkedin}}</p>
            <p>Github: {{contactInfo.github}}</p>

            <section>
                <h1>Skills</h1>
                <ul class="skill-set">
                    {% for skill in skills %}
                    <li>{{skill}}</li>
                    {% endfor %}
                </ul>
            </section>
        </div>
    </div>
    </div>
    <script src="{% static 'resume_app/js/script.js' %}"></script>
</body>
</html>

resume_app/templates/resume_app/resume2.html
<html>
	<head>
		{% load static %}

    <link rel="stylesheet" href="{% static 'styles/resume2.css' %}">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js">
    </script>
	</head>
	<body>
		<!-- <button id="download-button">generate PDF</button>
    <div id="editor"></div> -->
		<button class="btn btn-block no-print btn-success" onclick="window.print()">PRINT AS PDF</button>

		<div class='parent' id="content">
			<div class="right">
				<div class="inner">
					<div class="name-hero">
						<div class="name-text">
							<h3>{{name}} </h3>
						</div>

						<div class="title">
							<h3> {{title}} </h3>
						</div>
					</div>


					<div class="summary">
							<h1>Summary</h1>
							<p>{{summary}}</p>
					</div>
					<section>
							<h1>Employment</h1>
							{% for experience in workExperience %}
							<p><em>{{experience.dates}} | {{experience.company}} | {{experience.title}}</em></p>
							<!-- <p>{{experience.description}}</p> -->

							{% for line in experience.description %}
							<p>
									<li>{{line}}</li>
							</p>
							{% endfor %}

							{% endfor %}
					</section>
					<section>
							<h1>Education</h1>
							{% for edu in education %}
							<p><em>{{edu.dates}} | {{edu.school}} | {{edu.degree}}</em></p>
							<p>{{edu.description}}</p>

							{% endfor %}
					</section>


			</div>
		</div>
				<div class="left">
						<h2>Contact Information</h2>
						<p>Email: {{contactInfo.email}}</p>
						<p>Phone: {{contactInfo.phone}}</p>
						<p>Address: {{contactInfo.address}}</p>
						<!-- <p>LinkedIn: <a href="{{contactInfo.linkedin}}">LinkedIn Profile</a></p>
						<p>Github: <a href="{{contactInfo.github}}">GitHub Profile</a></p> -->
						<p>LinkedIn: {{contactInfo.linkedin}}</p>
						<p>Github: {{contactInfo.github}}</p>

						<section>
								<h1>Skills</h1>
								<p>
									<!-- <ul class="skill-set"> -->
											{% for skill in skills %}
											<li>{{skill}}</li>
											{% endfor %}
									<!-- </ul> -->
								</p>
						</section>
				</div>
		</div>
		</div>
		<script src="{% static 'resume_app/js/script.js' %}"></script>
	</body>
	
</html>